### ISSUE TITLE
[BUG] SIGSEGV while listing organizations

### ISSUE THREAD

**Issue by matclab** [esnet/gdg#120]
**Describe the bug**
Listing organization on a new grafana v9.3.1 instance with one organization configured gives a SIGSEGV fault :

```
$ docker run -it --rm -e GDG_CONTEXTS__PROD__TOKEN=$"$GDG_CONTEXTS__PROD__TOKEN" -v $(pwd):/app/conf -v ~/grafana-dashboards:/app/exports ghcr.io/esnet/gdg:latest -c /app/conf/gdg-config.yaml org list                        
INFO[0000] Listing organizations for context: 'prod'    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8241f1]

goroutine 1 [running]:
github.com/grafana-tools/sdk.(*Client).doRequest(0x0, {0x1193588?, 0xc00003a040}, {0xfbad68, 0x3}, {0xfc0384, 0x8}, 0x0, {0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/grafana-tools/sdk@v0.0.0-20220611090550-5c2631ac7ee4/rest-request.go:101 +0x71
github.com/grafana-tools/sdk.(*Client).get(...)
	/home/runner/go/pkg/mod/github.com/grafana-tools/sdk@v0.0.0-20220611090550-5c2631ac7ee4/rest-request.go:81
github.com/grafana-tools/sdk.(*Client).GetAllOrgs(0xf90ce0?, {0x1193588, 0xc00003a040})
	/home/runner/go/pkg/mod/github.com/grafana-tools/sdk@v0.0.0-20220611090550-5c2631ac7ee4/rest-org.go:59 +0x97
github.com/esnet/gdg/api.(*DashNGoImpl).ListOrganizations(0xc00040d480)
	/home/runner/work/gdg/gdg/api/organizations.go:13 +0x50
github.com/esnet/gdg/cmd.glob..func30(0x17c21e0?, {0xfbbb99?, 0x2?, 0x2?})
	/home/runner/work/gdg/gdg/cmd/organizations.go:25 +0x111
github.com/spf13/cobra.(*Command).execute(0x17c21e0, {0xc000114e80, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x17c2460)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/esnet/gdg/cmd.Execute()
	/home/runner/work/gdg/gdg/cmd/root.go:39 +0x25
main.main()
	/home/runner/work/gdg/gdg/main.go:18 +0x4a
```

**Desktop (please complete the following information):**
 - GDG Version: [e.g. 0.1.10 output of gdg version]
 ```
Build Date: 2022-12-02T20:29:24Z
Git Commit: 00fa74dcac2c1455742fde2544f6c0dee3bca132
Version: 0.3.1
Go Version: go1.19.3
OS / Arch: linux amd64
```
 - Grafana Version: `9.3.1`
 - Configuration for Importer
```
context_name: prod

contexts:
  prod:
    dashboards_output: /home/matclab/grafana-dashboards
    token: ""  # Set by env
    url: http://monitor.matclab.net/grafana
    organization: Antipodae
    ignore_filters: False  # When set to true all Watched filtered folders will be ignored and ALL folders will be acted on
    watched:
      - General

global:
  debug: true
  ignore_ssl_errors: false ##when set to true will ignore invalid SSL errors
```

**Comment by safaci2000** [comment]
The failure needs to be handled more cleanly for sure, but if you look at the documentation: https://grafana.com/docs/grafana/latest/developers/http_api/org/.

You'll see that "the admin of all organizations API only works with basic authentication, see [Admin Organizations API](https://grafana.com/docs/grafana/latest/developers/http_api/org/#admin-organizations-api) for more information."

Basically you NEED basic auth setup, tokens won't work.

**Comment by matclab** [comment]
Oups, I totally missed this point. Thank you for pointing it to me.

**Comment by safaci2000** [comment]
No worries. I pushed a small patch to make it a bit cleaner when it fails in the next version.  I'll close the ticket for now, if you run into anymore issues feel free to re-open.
